### ISSUE TITLE
Python Error Message when Building

### ISSUE THREAD

**Issue by Mechtilde** [Ericsson/exchangecalendar#388]
When building exchangecalendar for Debian I get the following error message:

Traceback (most recent call last):
  File "/usr/lib/icedove-devel/sdk/bin/typelib.py", line 290, in <module>
    idl.resolve(options.incdirs, p)
  File "/usr/lib/icedove-devel/sdk/bin/xpidl.py", line 287, in resolve
    p.resolve(self)
  File "/usr/lib/icedove-devel/sdk/bin/xpidl.py", line 257, in resolve
    raise IDLError("File '%s' not found" % self.filename, self.location)
xpidl.IDLError: error: File 'mivIxml2jxon.idl' not found, interfaces/exchangeItemsManager/mivExchangeItemsManager.idl line 25:0
#include "mivIxml2jxon.idl"
^

I found this with version 3.4.0 and 3.5.0~beta1

**Comment by bavincen** [comment]
@Mechtilde can you please explain, are you truing to build xpcom. 
or building ews calendar.
